[package]
name = "katamari"
version = "0.0.0"
description = "Aggregate RSS and friends."
edition = "2021"

[dependencies]
axum = "0.7"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
